
pipeline {
  agent{ label 'mini' }
  environment {
    LIB = load 'lib/Common.groovy'
    ib = "${JOB_BASE_NAME}"
    tb = "${ib[0..5]}"
    IbTitle = LIB.strIbTitle(ib)
    // runAllowed = LIB.getValueRedis(ib)
    cs = 'lib/create-script.os'
    CLADDR = 'obr-app-13'
    SQLSRV = 'obr-sql-01'
    SQLbackup = '\\\\192.168.3.56\\backup'
    VER1C = '8.3.18.1483'
    enCode = '0008'
    scPath = "${env.WORKSPACE}/SQL_${ib}.SQLscript"

  }
  stages {
    stage('0. Разрешение запуска'){
      steps{
        script {

          def deny = bat(script: "curl --silent -X GET http://mysql:8000/q/mc_zup_tst", returnStdout: true)
          
          echo "---------OK(Сухих):${deny}---------"
          def User = currentBuild.rawBuild.getCause(Cause.UserIdCause)
          if (null==User) {
            if (deny!="on") {
            echo "Сборка отменена (${deny})"
              currentBuild.result = 'SUCCESS'
              return
              }
          } else {
            echo "${User['userId']}"
          }
          
        }
      }
    }
  }
}
